name: Run Database Operations

on:
  push:
    branches:
      - main
      - develop  # Add develop branch trigger

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      # Etapa 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Etapa 2: Configurar o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      # Etapa 3: Instalar dependências do projeto (se necessário, por exemplo, requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Etapa 4: Rodar os testes apenas na branch develop
      - name: Run tests (only on develop branch)
        if: github.ref == 'refs/heads/develop'  # Run only on develop branch
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Etapa 5: Exibir os resultados do pytest
      - name: Show pytest results
        if: success() # Se o pytest passou, mostre o resultado
        run: |
          echo "Tests passed successfully!"

      # Handle test failures
      - name: Handle test failures
        if: failure() # Se o pytest falhou, mostre um erro
        run: |
          echo "Tests failed. Please check the logs above for errors."
